dist: trusty
language: python
python:
  - 2.7
  - 3.4
  - 3.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev
  - sudo apt-get install -y python-pyproj
install:
  - pip install -r requirements.txt
