dist: trusty
language: python
python:
  - 2.7
  - 3.4
  - 3.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev proj-bin
  - sudo apt-get install -y python-pyproj
  - wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-3_amd64.deb
  - sudo dpkg -i libproj-dev_4.9.2-3_amd64.deb
install:
  - pip install -r requirements.txt
